version: '3'
services:
  node:
    build: .
    working_dir: /es-node
    volumes:
      - ./es-data:/es-data
    command: [ "env miner=${miner} private_key=${private_key} ./run.sh" ]
    container_name: es
