version: '3'
services:
  node:
    build: .
    ports:
      - '9545:9545'
      - 0.0.0.0:${EL_P2P_PORT:-9222}:${EL_P2P_PORT:-9222}/tcp
      - 0.0.0.0:${EL_P2P_PORT:-30305}:${EL_P2P_PORT:-30305}/udp
    volumes:
      - ./es-data:/es-node/es-data
    environment:
      - ES_NODE_STORAGE_MINER=${ES_NODE_STORAGE_MINER}
      - ES_NODE_PRIVATE_KEY=${ES_NODE_PRIVATE_KEY}
    command: /es-node/run.sh
    container_name: es
