version: '3'
services:
  node:
    build: .
    volumes:
      - ./es-data:/es-node/es-data
    environment:
      - miner=${ES_NODE_STORAGE_MINER}
      - private_key=${ES_NODE_PRIVATE_KEY}
    command: /es-node/run.sh
    container_name: es
