version: '3'
services:
  node:
    build: .
    volumes:
      - ./es-data:/es-data
    command:
      [
        "/es-node/run.sh",
        "-m",
        "<miner>",
        "-p",
        "<private_key>"
      ]
    container_name: es
