version: '3'
services:
  node:
    build: .
    volumes:
      - ./es-data:/es-data
    environment:
      - miner=${miner}
      - private_key=${private_key}
    command: /es-node/run.sh
    container_name: es
